### PR TITLE
Decode outputs

### PR DESCRIPTION
**Pull request by ayrat555**
This PR should be merged after https://github.com/poanetwork/ex_abi/pull/34
Resolves https://github.com/poanetwork/ex_abi/issues/25

Now to decode/encode output you should pass data type `:output` as the third parameter. By default, the third parameter is `:input` For example

```elixir
      selector = %FunctionSelector{
        function: "getVersion",
        input_names: [],
        inputs_indexed: nil,
        method_id: <<13, 142, 110, 44>>,
        returns: [:string],
        type: :function,
        types: []
      }

      data =
        "0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d312e302e342b6136396337363300000000000000000000000000000000000000"
        |> Base.decode16!(case: :lower)

      expected_result = ["1.0.4+a69c763"]

      assert expected_result == ABI.decode(selector, data, :output)
      assert data == ABI.encode(selector, expected_result, :output)
```

### CODE REVIEW

**Comment by InoMurko** [comment]
KUDOS!

**Comment by ayrat555** [comment]
@vbaranov the third parameter is optional. So it will work like before

**Comment by vbaranov** [comment]
@ayrat555 I've tried example, you provided, but tried to decode with 2 parameters. Here is the result:
```
iex(6)> ABI.decode(selector, data)
** (MatchError) no match of right hand side value: {:ok, <<0, 0, 0, 0>>, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}
    (ex_abi 0.4.0) lib/abi/type_decoder.ex:143: ABI.TypeDecoder.decode/3
```

**Comment by ayrat555** [comment]
@vbaranov I think you're trying to decode output with input types. Different data should be provided for input

**Comment by ayrat555** [comment]
@vbaranov the function doesn't accept any parameters

**Comment by vbaranov** [comment]
@ayrat555 
> I think you're trying to decode output with input types. Different data should be provided for input

Maybe, we should gracefully handle this error?

> the function doesn't accept any parameters

what do you mean? which one?

**Comment by ayrat555** [comment]
> Maybe, we should gracefully handle this error?

I can work on it as a separate issue. It's the same behaviour that was before my changes

> what do you mean? which one?

getVersion - `types: []`

**Pull request merged**
